
describe ('register testovi', ( )=> {
    it('posetiti strancu', () => {
        cy.visit('/')
    })
    it('klikni na register', () => {
        cy.visit('/')
        cy.get('.nav-link').eq(2).click()
    })
    var email = "raderadovic" + Math.floor((Math.random() * 1000000) + 1) + "@test.com";
    it('unos podataka i submit', () => {
        cy.visit('/')
        cy.get('.nav-link').eq(2).click()
        cy.get('#first-name').type('Pera')
        cy.get('#last-name').type('Peric')
        cy.get('#email').type(email)
        cy.get('#password').type('test1234')
        cy.get('#password-confirmation').type('test1234')
        cy.get('.form-check-input').check()
        cy.get('button').click()
    })
    it('logout', () => {
        email = "raderadovic" + Math.floor((Math.random() * 1000000) + 1) + "@test.com";
        cy.visit('/')
        cy.get('.nav-link').eq(2).click()
        cy.get('#first-name').type('Pera')
        cy.get('#last-name').type('Peric')
        cy.get('#email').type(email)
        cy.get('#password').type('test1234')
        cy.get('#password-confirmation').type('test1234')
        cy.get('.form-check-input').check()
        cy.get('button').click()
        cy.get('.nav-link').should('have.length', 4)
        cy.get('.nav-link').eq(3).click()
    })
    it('pokusaj registracije sa postojecim mailom', () => {
        cy.visit('/')
        cy.get('.nav-link').eq(2).click()
        cy.get('#first-name').type('Pera')
        cy.get('#last-name').type('Peric')
        cy.get('#email').type('testhome@test.com')
        cy.get('#password').type('test1234')
        cy.get('#password-confirmation').type('test1234')
        cy.get('.form-check-input').check()
        cy.get('button').click()
    })
    it('pokusaj registracije bez imena', () => {
        email = "raderadovic" + Math.floor((Math.random() * 1000000) + 1) + "@test.com";
        cy.visit('/')
        cy.get('.nav-link').eq(2).click()
        cy.get('#last-name').type('Peric')
        cy.get('#email').type(email)
        cy.get('#password').type('test1234')
        cy.get('#password-confirmation').type('test1234')
        cy.get('.form-check-input').check()
        cy.get('button').click()
    })   
    it('pokusaj registracije bez prezimena', () => {
        email = "raderadovic" + Math.floor((Math.random() * 1000000) + 1) + "@test.com";
        cy.visit('/')
        cy.get('.nav-link').eq(2).click()
        cy.get('#first-name').type('Pera')
        cy.get('#email').type(email)
        cy.get('#password').type('test1234')
        cy.get('#password-confirmation').type('test1234')
        cy.get('.form-check-input').check()
        cy.get('button').click()
    })
    it('pokusaj registracije bez emaila', () => {
        cy.visit('/')
        cy.get('.nav-link').eq(2).click()
        cy.get('#first-name').type('Pera')
        cy.get('#last-name').type('Peric')
        cy.get('#password').type('test1234')
        cy.get('#password-confirmation').type('test1234')
        cy.get('.form-check-input').check()
        cy.get('button').click()
    }) 
    it('pokusaj registracije bez passworda', () => {
        email = "raderadovic" + Math.floor((Math.random() * 1000000) + 1) + "@test.com";
        cy.visit('/')
        cy.get('.nav-link').eq(2).click()
        cy.get('#first-name').type('Pera')
        cy.get('#last-name').type('Peric')
        cy.get('#email').type(email)
        cy.get('#password-confirmation').type('test1234')
        cy.get('.form-check-input').check()
        cy.get('button').click()
    })
    it('pokusaj registracije bez password confirmation', () => {
        email = "raderadovic" + Math.floor((Math.random() * 1000000) + 1) + "@test.com";
        cy.visit('/')
        cy.get('.nav-link').eq(2).click()
        cy.get('#first-name').type('Pera')
        cy.get('#last-name').type('Peric')
        cy.get('#email').type(email)
        cy.get('#password').type('test1234')
        cy.get('.form-check-input').check()
        cy.get('button').click()
    })
    it('pokusaj registracije check/uncheck terms', () => {
        email = "raderadovic" + Math.floor((Math.random() * 1000000) + 1) + "@test.com";
        cy.visit('/')
        cy.get('.nav-link').eq(2).click()
        cy.get('#first-name').type('Pera')
        cy.get('#last-name').type('Peric')
        cy.get('#email').type(email)
        cy.get('#password').type('test1234')
        cy.get('#password-confirmation').type('test1234')
        cy.get('.form-check-input').check()
        cy.get('.form-check-input').uncheck()
        cy.get('button').click()
    })
})